#config/redis.yml
default:
  host: localhost
  port: 6379
development:
  db: 0
  namespace: poke_brew
test:
  db: 1
  namespace: poke_brew
production:
  db: 2
  host: 192.168.1.100
  namespace: poke_brew
